VERILOG_SOURCES += ../../../../simWorkspace/SyncAdder/rtl/SyncAdder.v ../common/timescale.v
# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file:
TOPLEVEL=SyncAdder
# MODULE is the name of the Python test file:
MODULE=SyncAdderTest

include $(shell cocotb-config --makefiles)/Makefile.sim
