VERILOG_SOURCES += ../mips32.v
# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file:
TOPLEVEL=MIPS32
# MODULE is the name of the Python test file:
MODULE=MIPS32Test

include $(shell cocotb-config --makefiles)/Makefile.sim
