VERILOG_SOURCES += $(CODEGEN)/Adder.v $(CODEGEN)/enumdefine.v timescale.v
# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file:
TOPLEVEL=Adder
# MODULE is the name of the Python test file:
MODULE=test_adder

include $(shell cocotb-config --makefiles)/Makefile.sim
