name: RTL-CI
on:
  pull_request:
    branches: [main]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Run
        env:
          SHOW_WAVE: false
        run: |
          sudo apt-get install -y iverilog
          sudo apt-get install -y gtkwave
          ./run.sh
          cd spinal-rtl
          sudo apt-get install -y verilator
          sbt "runMain tbCounter"
