name: RTL-CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [cron: "0 */24 * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Check out Spinal-CocotbLib code
        uses: actions/checkout@v2
        with:
          repository: SpinalHDL/CocotbLib
          path: ./spinal-rtl/src/test/python/cocotblib
      - name: Run
        env:
          SHOW_WAVE: false
        run: |
          sudo apt-get update
          cd verilog-rtl
          sudo apt-get install -y iverilog yosys
          # sudo apt-get install -y gtkwave
          sudo apt-get install expect
          # Install TLV code generator
          pip3 install sandpiper-saas
          # Confirm sandpiper agreement
          ./src/riscv_pll/sandpiper-confirm.sh
          ./run.sh
          cd ../spinal-rtl
          sudo apt-get install -y verilator
          # sudo apt-get install -y lcov
          # sudo apt-get install python3-pip
          # Local install Cocotb and set PATH env
          pip3 install cocotb
          export PATH="$HOME/.local/bin:$PATH"
          #./run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

