name: LordOS-CI
on:
  pull_request:
    branches: [main]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        env:
          SHOW_WAVE: false
        run: |
          sudo apt-get install -y iverilog
          sudo apt-get install -y gtkwave
          ./run.sh
